name: mobile
description: "Mobile Client for BBO method"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  web_socket_channel: ^3.0.0
  fl_chart: ^0.70.2
  uuid: ^4.5.1
  equatable: ^2.0.7
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  shared_preferences: ^2.3.4
  intl: ^0.20.1
  image: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
